import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
});

const title = "Zyke — the AI marketing agent for your brand";
const description =
  "Zyke learned a brand's voice, tracked what was trending, and turned both into finished social posts with AI-generated images you could edit by pointing at them. Built at IIT Kharagpur in 2024. Watch the demo.";

export const metadata: Metadata = {
  metadataBase: new URL("https://zyke.in"),
  title,
  description,
  keywords: ["Zyke", "AI marketing agent", "brand voice", "social media content", "generative AI", "IIT Kharagpur"],
  openGraph: {
    title,
    description,
    type: "website",
    url: "https://zyke.in",
    siteName: "Zyke",
    images: [{ url: "/posts/Idea3Post2Img1.png", width: 640, height: 640, alt: "A post generated by Zyke" }],
  },
  twitter: { card: "summary_large_image", title, description, images: ["/posts/Idea3Post2Img1.png"] },
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
