import type { Metadata } from "next";
import localFont from "next/font/local";
import { Instrument_Serif } from "next/font/google";
import "./globals.css";

const sans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-sans",
  weight: "100 900",
  display: "swap",
});
const mono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-mono",
  weight: "100 900",
  display: "swap",
});
const serif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-serif",
  display: "swap",
});

const title = "Zyke";
const description =
  "Zyke was an AI marketing agent built at IIT Kharagpur in 2024. It learned a brand's voice, followed what was trending, and produced finished social posts with images you could edit by pointing at them. This is the record of what it was.";

export const metadata: Metadata = {
  metadataBase: new URL("https://zyke.in"),
  title,
  description,
  openGraph: {
    title: "Zyke — an AI marketing agent, 2024",
    description,
    type: "website",
    url: "https://zyke.in",
    siteName: "Zyke",
    images: [{ url: "/posts/Idea1Post1Img3.png", width: 512, height: 512, alt: "A post generated by Zyke" }],
  },
  twitter: { card: "summary_large_image", title, description, images: ["/posts/Idea1Post1Img3.png"] },
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable} ${serif.variable}`}>
      <body>{children}</body>
    </html>
  );
}
