// Every piece of copy and data on the page lives here so the components stay
// presentational.

export const site = {
  name: "Zyke",
  email: "founders@zyke.in",
  linkedin: "https://www.linkedin.com/company/zykelabs/",
  github: "https://github.com/zykelabs",
  githubFrontend: "https://github.com/zykelabs/zyke-frontend",
  githubBackend: "https://github.com/zykelabs/zyke-backend",
  youtubeId: "_z__HdAyjl8",
  youtubeUrl: "https://youtu.be/_z__HdAyjl8",
};

// Chapters follow the demo video's transcript.
export const chapters = [
  { t: 0, label: "0:00", title: "The landing page and the three promises" },
  { t: 33, label: "0:33", title: "Creating a brand voice, with Zomato as the example" },
  { t: 65, label: "1:05", title: "Picking a topic: a trend, or a blog or post to repurpose" },
  { t: 88, label: "1:28", title: "A live trend: SpaceX catches a Starship booster" },
  { t: 105, label: "1:45", title: "Zyke proposes ideas; you pick, or add your own" },
  { t: 136, label: "2:16", title: "Generating the posts: captions and two or three images each" },
  { t: 175, label: "2:55", title: "Editing an image by clicking on it and typing a prompt" },
  { t: 221, label: "3:41", title: "Original and edited, side by side" },
];

export const pillars = [
  { n: "I", title: "Aligned to your brand voice." },
  { n: "II", title: "Edited by pointing at the picture." },
  { n: "III", title: "Built from what was trending." },
];

export const steps = [
  { n: "1", title: "Brand research and voice", demo: "In the demo the brand is Zomato.", body: "Name and links in. Tone, emotion and character out, editable and saved." },
  { n: "2", title: "Ideas from what is trending", demo: "Trending that day: SpaceX catching a Starship booster.", body: "Live trends with a reason each. Pick one, paste a URL to repurpose, or type your own." },
  { n: "3", title: "Posts, in the brand\u2019s voice", demo: "Three ideas became nine posts.", body: "Captions from a reasoning model. Images from FLUX, one per beat of the story." },
  { n: "4", title: "Point, describe, done", demo: "Make the background darker and add a galaxy with some planets.", body: "Click, confirm the region, type the change. The scooter and the rider stay untouched." },
];

export const beforeAfter = {
  before: "/masks/L_Model_blended_img_1.png",
  after: "/generated/fixed.png",
  prompt: "Make the background darker and add a galaxy with some planets",
};

export const features = [
  { n: "01", title: "Brand research and profiling" },
  { n: "02", title: "Brand voice creation" },
  { n: "03", title: "Customer profile mapping" },
  { n: "04", title: "User engagement tracking" },
  { n: "05", title: "Dashboard with custom metrics" },
  { n: "06", title: "Trending topics, tailored" },
  { n: "07", title: "Personalised recommendations" },
  { n: "08", title: "Text, image and video generation" },
  { n: "09", title: "Click-to-segment image editing" },
  { n: "10", title: "Video storyboards" },
  { n: "11", title: "Moodboarding" },
  { n: "12", title: "Post attention analysis" },
  { n: "13", title: "Post-generation analysis" },
];

// Every image in the gallery was generated by Zyke during the demo run.
export const gallery = [
  { src: "/posts/Idea1Post1Img1.jpg", idea: "SpaceX vs Zomato", caption: "Boosters at 2,500 mph, your pizza in 25 minutes" },
  { src: "/posts/Idea1Post1Img2.png", idea: "SpaceX vs Zomato", caption: "Catching boosters, catching cravings" },
  { src: "/posts/Idea1Post1Img3.png", idea: "SpaceX vs Zomato", caption: "The precision infographic" },
  { src: "/posts/Idea2Post1Img1.png", idea: "Zomato Mission Control", caption: "Every order tracked like a launch" },
  { src: "/posts/Idea2Post1Img2.png", idea: "Zomato Mission Control", caption: "Delivery success, planted" },
  { src: "/posts/Idea2Post1Img3.png", idea: "Zomato Mission Control", caption: "Extra cheese engaged" },
  { src: "/posts/Idea3Post1Img1.png", idea: "The model's own idea", caption: "Blast off" },
  { src: "/posts/Idea3Post1Img2.png", idea: "The model's own idea", caption: "Same precision, different missions" },
  { src: "/posts/Idea3Post1Img3.png", idea: "The model's own idea", caption: "Hungry in space" },
  { src: "/posts/Idea3Post2Img1.png", idea: "The model's own idea", caption: "The image edited in the demo" },
  { src: "/posts/Idea3Post2Img2.png", idea: "The model's own idea", caption: "Rooftop landing" },
  { src: "/posts/Idea3Post3Img1.png", idea: "The model's own idea", caption: "Asteroid fries" },
  { src: "/posts/Idea3Post3Img2.png", idea: "The model's own idea", caption: "Chef in orbit" },
];

export const stack = [
  { layer: "Web app", items: ["Next.js 14, TypeScript, Tailwind", "Email sign-up with one-time codes", "Razorpay wallet for credits"] },
  { layer: "API", items: ["Flask on AWS EC2 in Mumbai, behind gunicorn", "MongoDB for users, brand voices, posts and transactions", "Eleven blueprints, twenty-seven routes"] },
  { layer: "Trends and recommendation", items: ["Google Trends daily searches for India, through pytrends", "Perplexity Sonar to explain why each topic is trending", "OpenAI o1-mini to score and rank trends per brand", "Six-hour caches, billed to a house account"] },
  { layer: "Language models", items: ["OpenAI o1-mini for ranking, ideas, captions and edit routing", "Llama 3.1 and GPT-4o mini (vision) for brand research", "Gemini 1.5 Flash for repurposing URLs"] },
  { layer: "Image generation", items: ["FLUX 1.1 Pro through Together AI, fifty steps", "Batches of four with a hand-rolled rate limiter"] },
  { layer: "Image editing", items: ["GraCo, granularity-controllable interactive segmentation, on a GPU", "Grounding DINO for open-vocabulary object detection", "Styling LoRAs for whole-image restyling", "Stability AI inpainting and image to image", "OpenCV locally for mask dilation and previews"] },
  { layer: "Data", items: ["Instagram and web scraping for brand research", "Google Cloud Storage for media", "Google Cloud Run and Modal for the GPU services"] },
];

export const timeline = [
  { when: "July 2024", what: "Version zero. One Flask route, one page, a prompt chain on Claude 3.5 Sonnet and FLUX." },
  { when: "August 2024", what: "Posts split per platform. Newer image model." },
  { when: "October 2024", what: "Rewritten in three weeks. Next.js app, Flask and MongoDB API, accounts, trends, payments." },
  { when: "November 2024", what: "Version 1.0. Click-to-segment editing on a GPU. The demo was recorded." },
  { when: "2025", what: "Wound down. The domain, the code and this page remain." },
];

// ---------------------------------------------------------------------------
// From the pitch deck, December 2024. Kept as it was written then.
// ---------------------------------------------------------------------------

export const problems = [
  { n: "01", title: "Agencies cost too much." },
  { n: "02", title: "The AI tools did not sound like you." },
  { n: "03", title: "In-house teams were guessing." },
];

export const coreNeed =
  "One tool that was efficient, affordable and actually personal to the brand.";

export const buyers = [
  {
    who: "Small firms",
    need: "Posts on trending topics, cheap enough to run every week.",
    quote:
      "We can give better services than UC but their brand is too big; they have funds large enough to afford crazy branding.",
    by: "Mayank Arya",
    role: "Founder",
  },
  {
    who: "Medium companies",
    need: "Brand-relevant content, produced often enough to grow visibility.",
    quote:
      "I would give you anything if you can give me better KPIs with measures on how to improve them.",
    by: "Akash Walia",
    role: "Marketing manager",
  },
  {
    who: "Large companies",
    need: "Creative work that moves brand positioning, not just fills a calendar.",
    quote:
      "We are a one stop solution, but we need to know what the customer is looking at majorly, so we can show that.",
    by: "Harshvardhan Chauhan",
    role: "Former CMO, retail",
  },
];

// Yes / no across Zyke and the three tools we were compared against.
export const comparison = {
  columns: ["Zyke", "Tool A", "Tool B", "Tool C"],
  rows: [
    { feature: "Trend analysis", values: [true, false, false, false] },
    { feature: "Personalised content generation", values: [true, true, true, true] },
    { feature: "Brand voice", values: [true, true, false, false] },
    { feature: "Repurpose existing content", values: [true, true, false, false] },
    { feature: "Prompt-based image editing", values: [true, false, false, false] },
    { feature: "Image generation", values: [true, true, false, true] },
  ],
};

export const economics = [
  { figure: "$0.05", label: "What one generated post cost us", note: "Model calls and storage for a single image." },
  { figure: "$0.20", label: "What we charged for it", note: "Pay as you go, once the free credits ran out." },
  { figure: "$0.70", label: "One brand voice, once", note: "Research, vision calls and the profile write-up." },
  { figure: "$5.00", label: "Free credits on sign-up", note: "Enough to make a real campaign before paying." },
];

export const market = [
  { figure: "$30.34B", label: "Total market we were sizing against" },
  { figure: "$2.2B", label: "The slice we could actually serve" },
  { figure: "36.2%", label: "Growth rate for AI in social media, to 2032" },
  { figure: "₹208 cr", label: "Spent on digital media by about a million Indian SMEs" },
];

export const marketerUse = [
  { pct: "33%", what: "Generate ideas and inspiration" },
  { pct: "28%", what: "Write copy and content" },
  { pct: "26%", what: "Create marketing images" },
];

export const team = [
  { name: "Tasmay P. Tibrewal", role: "CTO turned CEO", linkedin: "https://www.linkedin.com/in/tasmay-tibrewal/" },
  { name: "Rupam Mahato", role: "Founding engineer", linkedin: "https://www.linkedin.com/in/rupammahato/" },
  { name: "Siddharth Dikshit", role: "Co-founder and CEO until November. Left after the dispute.", linkedin: "" },
];

export const people = [
  { name: "Tasmay", role: "Founder", linkedin: "https://www.linkedin.com/in/tasmay-tibrewal/" },
  { name: "Rupam", role: "Founding member", linkedin: "https://www.linkedin.com/in/rupammahato/" },
];

export const grants = [
  { org: "Y Combinator", amount: "$25,000", what: "Startup school credits across cloud and tooling" },
  { org: "Modal Labs", amount: "$11,000", what: "GPU credits to serve the segmentation model" },
  { org: "Daytona", amount: "$10,000", what: "Development environment credits" },
  { org: "CampusFund", amount: "$5,000", what: "AWS credits to build the MVP" },
  { org: "Google Cloud for Startups", amount: "$2,000", what: "Cloud Run and storage" },
  { org: "Microsoft for Startups", amount: "$1,000", what: "Azure credits" },
  { org: "MongoDB for Startups", amount: "$500", what: "Database credits" },
];


// ---------------------------------------------------------------------------
// Work Zyke produced during testing, for Zomato, Bira 91, Nike and a coding
// school. We did not write these. Zyke read the day's trends, picked one,
// decided how to tie it to the brand, wrote the caption and generated the
// picture.
//
// Organised by month, because the month is the story. Between September and
// November 2024 we rebuilt the image stage twice, and the difference is visible
// without knowing anything about the code.
// ---------------------------------------------------------------------------

export type Piece = {
  src: string;
  w: number;
  h: number;
  brand: string;
  trend: string;
  caption: string;
};

export type Month = {
  id: string;
  month: string;
  res: string;
  headline: string;
  note: string;
  pieces: Piece[];
};

export const months: Month[] = [
  {
    id: "sept",
    month: "September 2024",
    res: "512 px",
    headline: "It could compose. It could not write.",
    note:
      "Zyke already found a trend, made the leap to the brand and built a picture around it. It just could not put a legible word on the canvas.",
    pieces: [
      { src: "/gallery/sept-rider-over-earth.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "A rider lifting off Earth on a pizza-fuelled exhaust trail." },
      { src: "/gallery/sept-scooter-and-rocket.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "A scooter watching a rocket leave with the delivery box strapped to it." },
      { src: "/gallery/sept-mission-control.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "A delivery mission control room. Fourteen screens, not one readable word on any of them." },
      { src: "/gallery/sept-booster-timeline.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "An attempt at a data story about delivery milestones." },
      { src: "/gallery/sept-bira-two-landmarks.jpeg", w: 512, h: 512, brand: "Bira 91", trend: "Going global", caption: "One bottle between the Statue of Liberty and the Eiffel Tower. The label almost holds together." },
      { src: "/gallery/sept-bira-citrus.jpeg", w: 512, h: 512, brand: "Bira 91", trend: "No trend", caption: "A split product shot, pineapple on one side and hard orange on the other." },
      { src: "/gallery/sept-beer-for-everyone.jpeg", w: 512, h: 512, brand: "Bira 91", trend: "No trend", caption: "Myth on the left, fact on the right, and a crowd disagreeing with the man in the suit." },
    ],
  },
  {
    id: "oct",
    month: "October 2024",
    res: "512 to 1024 px",
    headline: "Headlines start landing.",
    note:
      "We rewrote the pipeline and moved to FLUX 1.1 Pro. Short headlines and logos start landing; body copy still collapses.",
    pieces: [
      { src: "/gallery/oct-space-vs-delivery.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "Every word correct: how space delivers boosters, how Zomato delivers your pizza, same precision, different missions." },
      { src: "/gallery/oct-booster-chart.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "A bar chart nobody asked for. The bar labels are right, the headline above them is not." },
      { src: "/gallery/oct-aliens-and-fries.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The US alien files", caption: "Four aliens in orbit arguing over asteroid fries and galaxy sauce." },
      { src: "/gallery/oct-newspaper-front-page.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Prime Minister", caption: "An invented newspaper front page announcing Operation Zomato Feast." },
      { src: "/gallery/oct-indiacentury-menu.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "The Prime Minister", caption: "A four-panel campaign around a hashtag it made up." },
      { src: "/gallery/oct-rocket-and-scooter.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "A spec-sheet comparison between a rocket and a scooter." },
      { src: "/gallery/oct-moon-head.jpeg", w: 512, h: 512, brand: "Zomato", trend: "No trend", caption: "A man with the moon for a head feeding someone dinner." },
      { src: "/gallery/oct-bira-diwali.jpeg", w: 512, h: 512, brand: "Bira 91", trend: "Diwali", caption: "Two glasses meeting in front of a blurred rangoli of light." },
      { src: "/gallery/oct-bira-america.jpeg", w: 512, h: 512, brand: "Bira 91", trend: "Going global", caption: "Six bottles on a Stars and Stripes, lit like a product shoot. Every label spelled correctly." },
      { src: "/gallery/oct-bira-myth-and-fact.jpeg", w: 885, h: 437, brand: "Bira 91", trend: "Myths about beer", caption: "Two slides from a myth-and-fact carousel, including a calorie chart it invented the numbers for." },
      { src: "/gallery/oct-brewing-perfect-code.jpeg", w: 512, h: 512, brand: "A coding school", trend: "Developer culture", caption: "Half brewery, half editor, one chimp holding the sign." },
      { src: "/gallery/oct-lebron-spec-sheet.jpeg", w: 400, h: 400, brand: "Nike", trend: "Basketball season", caption: "A shoe spec sheet. The product name lands, the specifications are decorative." },
    ],
  },
  {
    id: "nov",
    month: "November 2024",
    res: "1024 to 1600 px",
    headline: "This is where it becomes consistent.",
    note:
      "Version 1.0. Full sentences hold, logos are right, and the same idea run twice comes back as the same campaign.",
    pieces: [
      { src: "/gallery/nov-smart-routing.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "Delhi traffic", caption: "Every word correct, twice, in two different type treatments, plus a clean logo lockup in the corner." },
      { src: "/gallery/nov-how-it-feels.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "Delhi traffic", caption: "Gridlock above, a rider getting through below." },
      { src: "/gallery/nov-delhi-landmarks.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "Delhi traffic", caption: "A red scooter throwing sparks past India Gate at sunset. One letter wrong in the whole picture." },
      { src: "/gallery/nov-stuck-in-traffic.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "Delhi traffic", caption: "Two panels, same rider." },
      { src: "/gallery/nov-scaling-heights-wide.jpeg", w: 1600, h: 1066, brand: "Zomato", trend: "The Prime Minister", caption: "The sharpest thing it ever made." },
      { src: "/gallery/nov-scaling-heights.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "The Prime Minister", caption: "The same idea in a square crop for a feed." },
      { src: "/gallery/nov-better-food-first-run.jpeg", w: 1600, h: 1066, brand: "Zomato", trend: "The Prime Minister", caption: "First run of a two-panel post. Left panel clean, right panel still garbling its own caption." },
      { src: "/gallery/nov-better-food-second-run.jpeg", w: 1600, h: 1066, brand: "Zomato", trend: "The Prime Minister", caption: "Second run of the same idea, minutes later." },
      { src: "/gallery/nov-cooking-better-india.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "The Prime Minister", caption: "A different register entirely, rendered as a 3D cartoon, with the headline and the sub-line both correct." },
      { src: "/gallery/nov-three-steps.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "No trend", caption: "Three stacked cards explaining a delivery." },
      { src: "/gallery/nov-eat-light.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "Get-ready-with-me", caption: "A four-panel beauty collage in purple, laid out on a real grid with consistent type across all four." },
      { src: "/gallery/nov-beauty-hacks.jpeg", w: 1024, h: 1024, brand: "Zomato", trend: "Get-ready-with-me", caption: "The same format on a white ground. Composition good, the floating labels never resolved." },
      { src: "/gallery/nov-lebron-confetti.jpeg", w: 844, h: 844, brand: "Nike", trend: "Basketball season", caption: "Confetti, a lit arena and a shoe in focus with the athlete deliberately thrown out of focus behind it." },
      { src: "/gallery/nov-empty-gym.jpeg", w: 340, h: 340, brand: "Nike", trend: "Basketball season", caption: "An empty gym, hard side light, one figure mid-shot." },
      { src: "/gallery/nov-court-shoes.jpeg", w: 340, h: 340, brand: "Nike", trend: "Basketball season", caption: "A close crop on the shoes with the court blurring past. Zyke chose the crop." },
      { src: "/gallery/nov-astronaut-flag.jpeg", w: 512, h: 512, brand: "Zomato", trend: "The Starship booster catch", caption: "A late 512 px run on an older idea, kept here because it shows the ceiling was the resolution rather than the idea." },
    ],
  },
];

// The three cards at the top of the section. Same pipeline, three months apart.
export const progression = [
  { id: "sept", when: "September 2024", size: "512 x 512", src: "/gallery/sept-mission-control.jpeg", w: 512, h: 512, what: "Fourteen screens, not one readable word. It could compose a scene and not label it." },
  { id: "oct", when: "October 2024", size: "512 to 1024", src: "/gallery/oct-booster-chart.jpeg", w: 512, h: 512, what: "Short lines land. The bars are labelled right, the headline above them is not." },
  { id: "nov", when: "November 2024", size: "1024 to 1600", src: "/gallery/nov-scaling-heights-wide.jpeg", w: 1600, h: 1066, what: "Full sentences, correct logos, and the same idea reproducible twice." },
];

// The pair that shows the November jump on its own.
export const sameIdeaTwice = {
  first: { src: "/gallery/nov-better-food-first-run.jpeg", w: 1600, h: 1066 },
  second: { src: "/gallery/nov-better-food-second-run.jpeg", w: 1600, h: 1066 },
};

// ---------------------------------------------------------------------------
// The image pipeline, and the things we had to build ourselves because they
// did not exist yet. All taken from the code.
// ---------------------------------------------------------------------------

export const era2024 = [
  "No Nano Banana, no GPT Image. No model would take a picture and a sentence and hand the picture back.",
  "Image models could not write. Text came out as letter shapes.",
  "A megapixel was the ceiling.",
  "A prompt with five requirements got two of them.",
  "Nothing stayed consistent between two runs.",
];

export const pipeline = [
  { n: "1", title: "One idea, several image prompts", body: "Asked for as XML, so the images in a post form a story instead of three takes on one picture." },
  { n: "2", title: "Brand voice as its own message", body: "A saved record, not a prompt template, injected on every single call." },
  { n: "3", title: "Four images at a time", body: "FLUX 1.1 Pro through Together AI, fifty steps, four cents an image." },
];

export const novelties = [
  "A reasoning model routing image edits by tool call, a year before that was a normal idea.",
  "One click returning several granularities, so the model asked what you meant.",
  "Open-vocabulary detection on the prompt, so you could name a thing instead of clicking it.",
  "Style by LoRA, not by prompt, so a restyle kept the picture.",
  "Mask previews on your own image, free to browse.",
  "Every edit applied to the original, with full undo.",
  "Trends scored per brand, from that brand\u2019s own history.",
  "Trends explained before being ranked.",
  "Trend, idea and post as three stages you could steer between.",
  "Every generation metered to the cent.",
];

// The leaps Zyke made on its own, from a headline to a brand. Nobody wrote
// these connections down for it.
export const leaps = [
  {
    trend: "The US government released its files on unidentified objects",
    brand: "Zomato",
    leap:
      "Alien files were the story of the week. It decided that if aliens are real, they are a market. The asteroid fries are its words.",
    shots: [
      { src: "/gallery/oct-aliens-and-fries.jpeg", w: 512, h: 512, when: "Oct" },
    ],
  },
  {
    trend: "The Prime Minister was all over the Indian news",
    brand: "Zomato",
    leap:
      "It saw one name in most of the news cycle and went for a national endorsement. Nobody asked it for a politician. It invented the hashtag too.",
    shots: [
      { src: "/gallery/oct-newspaper-front-page.jpeg", w: 512, h: 512, when: "Oct" },
      { src: "/gallery/nov-scaling-heights.jpeg", w: 1024, h: 1024, when: "Nov" },
      { src: "/gallery/nov-cooking-better-india.jpeg", w: 1024, h: 1024, when: "Nov" },
    ],
  },
  {
    trend: "SpaceX caught a Starship booster with the launch tower",
    brand: "Zomato",
    leap:
      "Catching a booster and getting an order right are the same claim about precision. It pushed that until it had built a chart of it.",
    shots: [
      { src: "/gallery/sept-mission-control.jpeg", w: 512, h: 512, when: "Sept" },
      { src: "/gallery/oct-space-vs-delivery.jpeg", w: 512, h: 512, when: "Oct" },
      { src: "/gallery/oct-booster-chart.jpeg", w: 512, h: 512, when: "Oct" },
    ],
  },
  {
    trend: "Delhi traffic",
    brand: "Zomato",
    leap:
      "The least exotic trend it picked, and the closest to the product. The city cannot move; the riders still do.",
    shots: [
      { src: "/gallery/nov-delhi-landmarks.jpeg", w: 1024, h: 1024, when: "Nov" },
      { src: "/gallery/nov-smart-routing.jpeg", w: 1024, h: 1024, when: "Nov" },
      { src: "/gallery/nov-how-it-feels.jpeg", w: 1024, h: 1024, when: "Nov" },
    ],
  },
  {
    trend: "Indian brands going abroad",
    brand: "Bira 91",
    leap:
      "It read the export story in the business press and made a travel series, one skyline at a time.",
    shots: [
      { src: "/gallery/sept-bira-two-landmarks.jpeg", w: 512, h: 512, when: "Sept" },
      { src: "/gallery/oct-bira-america.jpeg", w: 512, h: 512, when: "Oct" },
    ],
  },
  {
    trend: "Basketball season",
    brand: "Nike",
    leap:
      "A different category. It shot the product shallow with the athlete out of focus behind, which is how that category actually shoots.",
    shots: [
      { src: "/gallery/oct-lebron-spec-sheet.jpeg", w: 400, h: 400, when: "Oct" },
      { src: "/gallery/nov-lebron-confetti.jpeg", w: 844, h: 844, when: "Nov" },
      { src: "/gallery/nov-empty-gym.jpeg", w: 340, h: 340, when: "Nov" },
    ],
  },
];

// Why we started and why it stopped. Written plainly, on purpose.
export const ambition = [
  { n: "01", title: "The posts were never the point", body: "The goal was a content pipeline that ran itself, for a brand it already knew." },
  { n: "02", title: "Two engines", body: "A trend engine watching the news, and a brand engine that read hundreds of pages of a company into a researched model of it." },
  { n: "03", title: "The far end was not marketing", body: "The same machinery points at entertainment. Roughly what Higgsfield does now, with trends and brand research on the front." },
  { n: "04", title: "And I wanted to build something", body: "I came into college too ambitious to sit still. Zyke was that as much as it was a business." },
];

export const failure = [
  "We did not reach out enough. We should have been in front of brands every week. We were not.",
  "We never properly understood what a marketing team needs day to day. We did not do enough customer research, so most decisions came out of our own guesses.",
  "We could not sell. There was a working product and a demo people liked, and nothing behind it.",
  "We never got real pilots running. A few companies tried it. That is not the same as one brand using it every week and telling you what is broken.",
  "Everything we were good at sat on one side of the business. The other side stayed empty.",
];

export const failureClose =
  "Then there were co-founder disputes, and with the outreach already stalled there was not much holding it together. It ended there. I was in my third year and left for an internship. The lesson is not subtle: building the hard part turned out not to be the hard part.";

// ---------------------------------------------------------------------------
// The two engines worth describing in detail: the trend recommender, and the
// image editing router. The recommender is all in the archived backend. The
// editing router mostly ran as a separate GPU service whose source is not in
// these repos, so that part is written from memory and from the calls the
// frontend made into it.
// ---------------------------------------------------------------------------

export const recommender = [
  { n: "1", title: "Pull the day\u2019s searches", body: "Google Trends daily trending searches for India, on an IST clock." },
  { n: "2", title: "Ask why, not what", body: "Perplexity explained why each topic was trending right now. A brand can react to a reason, not a noun." },
  { n: "3", title: "Score it against the brand", body: "o1-mini ranked every trend 1 to 10 using the company research and the brand\u2019s own past posts." },
  { n: "4", title: "Score it differently per brand", body: "Creative brands got pushed toward the strange leaps. Traditional brands got pushed away from them." },
  { n: "5", title: "Return ideas, not posts", body: "You saw the ranking, the reasoning and several ideas, and chose. A checkbox let it add one of its own." },
  { n: "6", title: "Cache it, do not charge for it", body: "Six-hour caches, billed to a house account. Finding out what was happening was free." },
];

export const editing = [
  { n: "1", title: "A model picks the workflow", body: "Your sentence and the image went to o1-mini, which chose between four pipelines and ran it." },
  { n: "2", title: "Click, at the granularity you meant", body: "GraCo returned several masks for one ambiguous click. The jacket, the rider, or both. You picked." },
  { n: "3", title: "No target, change everything", body: "Image to image over the whole frame. Composition holds, the look moves." },
  { n: "4", title: "Name a thing, find a thing", body: "Grounding DINO located it from the prompt. Modify inside the mask, or remove and infill behind it." },
  { n: "5", title: "Restyle with a LoRA", body: "Prompt-only restyling redrew the picture. A LoRA kept the content and moved the treatment." },
  { n: "6", title: "See the mask before you pay", body: "Candidates dilated and lit up on your own image, locally, for free." },
  { n: "7", title: "Always edit the original", body: "Never the last result, with full undo. Five edits still looked like one picture." },
  { n: "8", title: "Force it to blend", body: "A long negative prompt, written by trial and error, to stop half-filled holes and seams." },
];

// Every collapsible section, in page order. Drives the nav and the contents list.
export const sections = [
  { id: "product", n: "01", label: "Product", name: "What it did", line: "Brand voice, live trends, and posts you could edit by pointing at them." },
  { id: "work", n: "02", label: "Work", name: "What it made", line: "Three months of output, and how fast it stopped looking like a machine." },
  { id: "machine", n: "03", label: "Machine", name: "How it was built", line: "A trend recommender, an image pipeline, and a router over four editing workflows." },
  { id: "business", n: "04", label: "Business", name: "Who it was for", line: "The problem, the buyers, and four cents of margin a post." },
  { id: "story", n: "05", label: "Story", name: "What happened", line: "Five months, three people, fifty thousand in credits, and why it stopped." },
];

// ---------------------------------------------------------------------------
// The short version, for anyone who does not want to read eleven sections.
// ---------------------------------------------------------------------------

export const summaryStats = [
  { figure: "4", label: "brands" },
  { figure: "3", label: "months" },
  { figure: "$0.05", label: "a post to make" },
  { figure: "$50k+", label: "in credits, no cash" },
];

export const summarySteps = [
  { n: "01", label: "Brand", line: "Read the site and the socials. Save a voice." },
  { n: "02", label: "Trend", line: "Rank the day's trends against that voice." },
  { n: "03", label: "Post", line: "Write the caption, generate the images." },
  { n: "04", label: "Edit", line: "Point at the picture, type the fix." },
];

export const summaryWork = [
  { src: "/gallery/nov-scaling-heights.jpeg", w: 1024, h: 1024, line: "It picked the Prime Minister out of the news and wrote a national endorsement." },
  { src: "/gallery/nov-delhi-landmarks.jpeg", w: 1024, h: 1024, line: "Delhi traffic, for a delivery brand." },
  { src: "/gallery/oct-aliens-and-fries.jpeg", w: 512, h: 512, line: "The US released its alien files, so it started selling to aliens." },
  { src: "/gallery/nov-smart-routing.jpeg", w: 1024, h: 1024, line: "Every word correct, by November." },
  { src: "/gallery/oct-space-vs-delivery.jpeg", w: 512, h: 512, line: "A booster catch became a claim about precision." },
  { src: "/gallery/nov-lebron-confetti.jpeg", w: 844, h: 844, line: "A different category, shot the way that category shoots." },
];

export const summaryTech = [
  { label: "Trends", line: "Google Trends, explained by Perplexity, ranked per brand by o1-mini." },
  { label: "Text", line: "o1-mini, with the saved brand voice on every call." },
  { label: "Images", line: "FLUX 1.1 Pro, four at a time." },
  { label: "Editing", line: "A router over four pipelines: GraCo, Grounding DINO, LoRAs, inpainting." },
];
