"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { gallery } from "@/lib/content";
import { Section } from "./Section";

export function Gallery() {
  const [open, setOpen] = useState<number | null>(null);

  useEffect(() => {
    if (open === null) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(null);
      if (e.key === "ArrowRight") setOpen((i) => (i === null ? i : (i + 1) % gallery.length));
      if (e.key === "ArrowLeft") setOpen((i) => (i === null ? i : (i - 1 + gallery.length) % gallery.length));
    };
    window.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [open]);

  return (
    <>
      <Section
        id="gallery"
        n="05"
        label="The output"
        title="Thirteen images, one afternoon, no stock photos."
        lede="Three ideas about a rocket landing, rewritten for a food-delivery brand. Every image here was generated by Zyke during the demo run."
      >
        <ol className="grid grid-cols-2 gap-x-3 gap-y-8 sm:grid-cols-3 lg:grid-cols-4">
          {gallery.map((g, i) => (
            <li key={g.src}>
              <button onClick={() => setOpen(i)} className="group block w-full text-left">
                <span className="plate block">
                  <Image
                    src={g.src}
                    alt={g.caption}
                    width={512}
                    height={512}
                    className="aspect-square w-full object-cover transition-opacity group-hover:opacity-90"
                  />
                </span>
                <span className="mt-2 block text-[13px] leading-snug">{g.caption}</span>
                <span className="block text-[12px] text-mute">{g.idea}</span>
              </button>
            </li>
          ))}
        </ol>
      </Section>

      {open !== null && (
        <div
          className="fixed inset-0 z-50 grid place-items-center bg-ink/95 p-6"
          onClick={() => setOpen(null)}
          role="dialog"
          aria-modal
          aria-label={gallery[open].caption}
        >
          <button className="absolute right-6 top-5 text-[13px] text-paper/80 hover:text-paper" onClick={() => setOpen(null)}>
            Close
          </button>
          <figure className="w-full max-w-[min(90vw,78vh)]" onClick={(e) => e.stopPropagation()}>
            <Image src={gallery[open].src} alt={gallery[open].caption} width={1024} height={1024} className="aspect-square w-full object-contain" />
            <figcaption className="mt-4 flex items-baseline justify-between gap-6 text-[13px] text-paper/80">
              <span>
                {gallery[open].caption} <span className="text-paper/50">· {gallery[open].idea}</span>
              </span>
              <span className="flex gap-4 font-mono text-xs">
                <button onClick={() => setOpen((open - 1 + gallery.length) % gallery.length)} className="hover:text-paper">
                  ← prev
                </button>
                <span>
                  {open + 1}/{gallery.length}
                </span>
                <button onClick={() => setOpen((open + 1) % gallery.length)} className="hover:text-paper">
                  next →
                </button>
              </span>
            </figcaption>
          </figure>
        </div>
      )}
    </>
  );
}
