import Image from "next/image";
import { steps, beforeAfter } from "@/lib/content";
import { Section } from "./Section";
import { BeforeAfter } from "./BeforeAfter";

export function HowItWorked() {
  return (
    <Section id="how" eyebrow="How it worked" title="One brand, one trend, nine posts, one edit. The demo, step by step.">
      <p className="max-w-2xl text-ink-300">
        The whole product was a pipeline. Each stage handed a richer object to the next: brand, then idea, then post,
        then a corrected image. You could stop and steer at any stage.
      </p>

      <ol className="mt-12 space-y-6">
        {steps.map((s, i) => (
          <li
            key={s.n}
            className="grid gap-6 rounded-2xl border hairline bg-ink-900/50 p-6 sm:p-8 lg:grid-cols-[64px_1fr_minmax(0,380px)]"
          >
            <div className="font-mono text-4xl font-medium text-ink-600">{s.n}</div>
            <div>
              <h3 className="text-xl font-semibold tracking-tight sm:text-2xl">{s.title}</h3>
              <p className="mt-2 font-mono text-[13px] leading-relaxed text-ember-300">{s.demo}</p>
              <p className="mt-4 text-[15px] leading-relaxed text-ink-300">{s.body}</p>
            </div>
            <div className="lg:justify-self-end">
              {i === 0 && <BrandVoiceCard />}
              {i === 1 && <TrendCard />}
              {i === 2 && s.image && (
                <figure className="overflow-hidden rounded-xl border hairline">
                  <Image src={s.image} alt="Infographic post generated by Zyke" width={512} height={512} className="aspect-square w-full object-cover" />
                  <figcaption className="px-3 py-2 font-mono text-[11px] text-ink-400">
                    Idea 1 · post 1 · image 3 of 3
                  </figcaption>
                </figure>
              )}
              {i === 3 && <BeforeAfter {...beforeAfter} />}
            </div>
          </li>
        ))}
      </ol>
    </Section>
  );
}

// A faithful, static recreation of the brand voice form in the demo.
function BrandVoiceCard() {
  const rows: [string, string][] = [
    ["Brand", "Zomato"],
    ["Type", "Product-based"],
    ["Tone", "Playful, quick, a little cheeky"],
    ["Emotion", "Delight, mild chaos"],
    ["Character", "The witty friend who always knows where to eat"],
  ];
  return (
    <div className="w-full rounded-xl border hairline bg-ink-950 p-4 text-sm">
      <div className="mb-3 flex items-center justify-between">
        <span className="font-mono text-[11px] uppercase tracking-widest text-ink-400">brand voice</span>
        <span className="rounded-full bg-emerald-500/15 px-2 py-0.5 font-mono text-[10px] text-emerald-300">saved</span>
      </div>
      <dl className="space-y-2.5">
        {rows.map(([k, v]) => (
          <div key={k} className="grid grid-cols-[84px_1fr] gap-3">
            <dt className="text-ink-500">{k}</dt>
            <dd className="text-ink-100">{v}</dd>
          </div>
        ))}
      </dl>
    </div>
  );
}

function TrendCard() {
  const trends = [
    { t: "SpaceX catches Starship booster", on: true },
    { t: "Diwali sales week", on: false },
    { t: "IPL auction rumours", on: false },
    { t: "Monsoon delays in Mumbai", on: false },
  ];
  const ideas = [
    { t: "SpaceX vs Zomato: precision infographic", on: true },
    { t: "Zomato Mission Control", on: true },
    { t: "Boosters vs biryani: the countdown", on: false },
    { t: "Let the AI add one more idea", on: true, ai: true },
  ];
  return (
    <div className="w-full space-y-3 text-sm">
      <div className="rounded-xl border hairline bg-ink-950 p-4">
        <p className="mb-2 font-mono text-[11px] uppercase tracking-widest text-ink-400">trending now</p>
        <ul className="space-y-1.5">
          {trends.map((x) => (
            <li key={x.t} className="flex items-center gap-2">
              <span className={x.on ? "h-3.5 w-3.5 rounded-full border-4 border-ember-500" : "h-3.5 w-3.5 rounded-full border border-ink-500"} />
              <span className={x.on ? "text-white" : "text-ink-400"}>{x.t}</span>
            </li>
          ))}
        </ul>
      </div>
      <div className="rounded-xl border hairline bg-ink-950 p-4">
        <p className="mb-2 font-mono text-[11px] uppercase tracking-widest text-ink-400">ideas in your voice</p>
        <ul className="space-y-1.5">
          {ideas.map((x) => (
            <li key={x.t} className="flex items-center gap-2">
              <span
                className={
                  x.on
                    ? "grid h-3.5 w-3.5 place-items-center rounded-[3px] bg-ember-500 text-[9px] font-bold text-ink-950"
                    : "h-3.5 w-3.5 rounded-[3px] border border-ink-500"
                }
              >
                {x.on ? "✓" : ""}
              </span>
              <span className={x.on ? "text-white" : "text-ink-400"}>{x.t}</span>
              {x.ai && <span className="ml-auto rounded bg-sky-500/15 px-1.5 py-0.5 font-mono text-[10px] text-sky-300">ai</span>}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
